// @ts-nocheck
// This file is generated by packages/server/scripts/generate-static-ui-assets.ts.

import asset0 from "../../ui/dist/apple-touch-icon.png" with { type: "file" };
import asset1 from "../../ui/dist/assets/index-BcfcVEZW.css" with { type: "file" };
import asset2 from "../../ui/dist/assets/index-CE6CF1wM.js" with { type: "file" };
import asset3 from "../../ui/dist/favicon-96x96.png" with { type: "file" };
import asset4 from "../../ui/dist/favicon.ico" with { type: "file" };
import asset5 from "../../ui/dist/favicon.svg" with { type: "file" };
import asset6 from "../../ui/dist/index.html" with { type: "file" };
import asset7 from "../../ui/dist/site.webmanifest" with { type: "file" };
import asset8 from "../../ui/dist/web-app-manifest-192x192.png" with { type: "file" };
import asset9 from "../../ui/dist/web-app-manifest-512x512.png" with { type: "file" };

export const staticUiAssets: Record<string, string> = {
  "/apple-touch-icon.png": asset0,
  "/assets/index-BcfcVEZW.css": asset1,
  "/assets/index-CE6CF1wM.js": asset2,
  "/favicon-96x96.png": asset3,
  "/favicon.ico": asset4,
  "/favicon.svg": asset5,
  "/index.html": asset6,
  "/site.webmanifest": asset7,
  "/web-app-manifest-192x192.png": asset8,
  "/web-app-manifest-512x512.png": asset9,
};
